stages:
  prepare:
    cmd: python src/stages/prepare.py tests/fixtures/sample_dataset.csv data/prepared
    deps:
      - tests/fixtures/sample_dataset.csv
      - src/stages/prepare.py
    outs:
      - data/prepared

  train:
    cmd: python src/stages/train.py data/prepared data/models --tracking-uri file:/opt/airflow/project/mlruns --experiment-name airflow_demo_pipeline
    deps:
      - data/prepared
      - src/stages/train.py
    outs:
      - data/models
